### ISSUE TITLE
Crafting Table Recipe

### ISSUE THREAD

**Issue by janagyjr** [orionSquared/Bnilla#1]
The recipe for a crafting table doesn't work.

![image](https://user-images.githubusercontent.com/23646259/29802266-bca8a47e-8c39-11e7-92fb-a674a556e0b0.png)

![image](https://user-images.githubusercontent.com/23646259/29802276-c69185aa-8c39-11e7-99ee-649cf897508e.png)

The recipe clearly says 'accepts any plankWood but the crafting gui doesn't register a valid recipe for oak planks.

**Comment by orionSquared** [comment]
Super weird. Pretty sure I messed up the custom recipe. I'll fix it this weekend.

**Comment by janagyjr** [comment]
Okay, I'll be waiting for the fix before coming back to my sp world.

On Aug 31, 2017 09:12, "orionSquared" <notifications@github.com> wrote:

Super weird. Pretty sure I messed up the custom recipe. I'll fix it this
weekend.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/orionSquared/Bnilla/issues/1#issuecomment-326307732>,
or mute the thread

**Comment by orionSquared** [comment]
Recipe fixed in 1.1 version of the pack.
